on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  push_artifacts:
    name: Push build artifacts to repo
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Download keymap image
        uses: actions/download-artifact@v4
        with:
          name: keymap-image
          path: keymap

      - name: Commit and push artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add firmware/ keymap/
          git commit -m "Update firmware and keymap image from latest successful build" || echo "No changes to commit"
          git push
