on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  firmware-management:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts
      
      - name: Create and clear firmware folder
        run: |
          rm -rf firmware
          mkdir -p firmware
      
      - name: Copy firmware files to firmware folder
        run: |
          find downloaded-artifacts -name "*.uf2" -exec cp {} firmware/ \;
          ls -la firmware/
      
      - name: Configure git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit firmware files
        run: |
          git add firmware/
          git diff --cached --quiet || git commit -m "Add firmware from workflow run ${{ github.run_id }}"
      
      - name: Push firmware files to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:${{ github.ref }}

      - name: Upload firmware folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.job }}-${{ github.run_id }}
          path: firmware/
          retention-days: 90
